#!/usr/bin/env python3
"""
Visualization tool for price data CSV files generated by the exchange simulator.

Usage:
    python tools/visualize_price_data.py [csv_file]
    
    If no file is specified, it will look for the most recent price_data_seed_*.csv file
    in the data/ directory.
"""

import sys
import os
import glob
import re

try:
    import pandas as pd
    import matplotlib.pyplot as plt
    import matplotlib.dates as mdates
except ImportError as e:
    print("Error: Required Python packages not installed.")
    print("Please install them using:")
    print("  pip install -r tools/requirements.txt")
    print("\nOr manually:")
    print("  pip install pandas matplotlib")
    sys.exit(1)

from pathlib import Path
from datetime import datetime, timedelta


def find_latest_csv(data_dir="data"):
    """Find the most recent price_data_seed_*.csv file."""
    pattern = os.path.join(data_dir, "price_data_seed_*.csv")
    files = glob.glob(pattern)
    if not files:
        return None
    # Sort by modification time, most recent first
    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]


def load_price_data(csv_file):
    """Load and prepare price data from CSV."""
    df = pd.read_csv(csv_file)
    
    # Convert timestamp from nanoseconds to datetime
    # Assuming timestamps are nanoseconds since epoch
    df['timestamp'] = pd.to_datetime(df['timestamp_ns'], unit='ns')
    
    # Sort by timestamp to ensure correct order
    df = df.sort_values('timestamp')
    
    return df


def extract_seed_from_filename(csv_file):
    """Extract seed number from CSV filename like 'price_data_seed_42.csv'."""
    match = re.search(r'price_data_seed_(\d+)\.csv', csv_file)
    if match:
        return match.group(1)
    return None


def create_visualizations(df, output_dir="data", seed=None):
    """Create multiple visualizations of the price data.
    
    Args:
        df: DataFrame with price data
        output_dir: Directory to save output images
        seed: Optional seed number to include in filename
    """
    
    # Create figure with subplots
    fig = plt.figure(figsize=(16, 12))
    
    # 1. Price over time (main chart)
    ax1 = plt.subplot(3, 2, (1, 2))
    ax1.plot(df['timestamp'], df['price'], linewidth=0.8, alpha=0.7, color='#2E86AB')
    ax1.set_title('Price Over Time', fontsize=14, fontweight='bold')
    ax1.set_xlabel('Time', fontsize=11)
    ax1.set_ylabel('Price (ticks)', fontsize=11)
    ax1.grid(True, alpha=0.3)
    ax1.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
    plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45, ha='right')
    
    # Add statistics text
    price_min = df['price'].min()
    price_max = df['price'].max()
    price_avg = df['price'].mean()
    price_range = price_max - price_min
    stats_text = f'Min: {price_min} | Max: {price_max} | Avg: {price_avg:.2f} | Range: {price_range}'
    ax1.text(0.02, 0.98, stats_text, transform=ax1.transAxes, 
              verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5),
              fontsize=9)
    
    # 2. Price distribution histogram
    ax2 = plt.subplot(3, 2, 3)
    ax2.hist(df['price'], bins=50, color='#A23B72', alpha=0.7, edgecolor='black')
    ax2.set_title('Price Distribution', fontsize=12, fontweight='bold')
    ax2.set_xlabel('Price (ticks)', fontsize=10)
    ax2.set_ylabel('Frequency', fontsize=10)
    ax2.grid(True, alpha=0.3, axis='y')
    ax2.axvline(price_avg, color='red', linestyle='--', linewidth=2, label=f'Mean: {price_avg:.2f}')
    ax2.legend()
    
    # 3. Volume over time
    ax3 = plt.subplot(3, 2, 4)
    # Aggregate volume by time windows (e.g., every 100 trades)
    window_size = max(1, len(df) // 50)  # ~50 data points
    df_vol = df.groupby(df.index // window_size).agg({
        'quantity': 'sum',
        'timestamp': 'first'
    })
    ax3.bar(range(len(df_vol)), df_vol['quantity'], color='#F18F01', alpha=0.7)
    ax3.set_title('Trading Volume (Aggregated)', fontsize=12, fontweight='bold')
    ax3.set_xlabel('Time Window', fontsize=10)
    ax3.set_ylabel('Total Volume', fontsize=10)
    ax3.grid(True, alpha=0.3, axis='y')
    
    # 4. Price change distribution
    ax4 = plt.subplot(3, 2, 5)
    price_changes = df['price'].diff().dropna()
    ax4.hist(price_changes, bins=50, color='#C73E1D', alpha=0.7, edgecolor='black')
    ax4.set_title('Price Change Distribution', fontsize=12, fontweight='bold')
    ax4.set_xlabel('Price Change (ticks)', fontsize=10)
    ax4.set_ylabel('Frequency', fontsize=10)
    ax4.grid(True, alpha=0.3, axis='y')
    ax4.axvline(0, color='black', linestyle='-', linewidth=1)
    ax4.axvline(price_changes.mean(), color='red', linestyle='--', linewidth=2, 
                label=f'Mean: {price_changes.mean():.2f}')
    ax4.legend()
    
    # 5. Cumulative volume-weighted average price (VWAP)
    ax5 = plt.subplot(3, 2, 6)
    df['cumulative_notional'] = (df['price'] * df['quantity']).cumsum()
    df['cumulative_volume'] = df['quantity'].cumsum()
    df['vwap'] = df['cumulative_notional'] / df['cumulative_volume']
    
    ax5.plot(df['timestamp'], df['vwap'], linewidth=2, color='#6A994E', label='VWAP')
    ax5.plot(df['timestamp'], df['price'], linewidth=0.5, alpha=0.3, color='gray', label='Trade Price')
    ax5.set_title('Volume-Weighted Average Price (VWAP)', fontsize=12, fontweight='bold')
    ax5.set_xlabel('Time', fontsize=10)
    ax5.set_ylabel('Price (ticks)', fontsize=10)
    ax5.legend()
    ax5.grid(True, alpha=0.3)
    ax5.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
    plt.setp(ax5.xaxis.get_majorticklabels(), rotation=45, ha='right')
    
    plt.tight_layout()
    
    # Save figure with seed tag if available
    if seed:
        output_file = os.path.join(output_dir, f'price_visualization_seed_{seed}.png')
    else:
        output_file = os.path.join(output_dir, 'price_visualization.png')
    plt.savefig(output_file, dpi=150, bbox_inches='tight')
    print(f"Visualization saved to: {output_file}")
    
    # Also create a simple price chart
    fig2, ax = plt.subplots(figsize=(12, 6))
    ax.plot(df['timestamp'], df['price'], linewidth=1, color='#2E86AB')
    ax.fill_between(df['timestamp'], df['price'], alpha=0.3, color='#2E86AB')
    title = f'Price Over Time - Simple View'
    if seed:
        title += f' (Seed: {seed})'
    ax.set_title(title, fontsize=14, fontweight='bold')
    ax.set_xlabel('Time', fontsize=11)
    ax.set_ylabel('Price (ticks)', fontsize=11)
    ax.grid(True, alpha=0.3)
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%H:%M:%S'))
    plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha='right')
    
    if seed:
        output_file_simple = os.path.join(output_dir, f'price_simple_seed_{seed}.png')
    else:
        output_file_simple = os.path.join(output_dir, 'price_simple.png')
    plt.savefig(output_file_simple, dpi=150, bbox_inches='tight')
    print(f"Simple chart saved to: {output_file_simple}")
    
    plt.close('all')
    
    # Print summary statistics
    print("\n" + "="*70)
    print("PRICE DATA SUMMARY")
    print("="*70)
    print(f"Total Trades: {len(df):,}")
    print(f"Time Range: {df['timestamp'].min()} to {df['timestamp'].max()}")
    print(f"Duration: {df['timestamp'].max() - df['timestamp'].min()}")
    print(f"\nPrice Statistics:")
    print(f"  Min: {price_min}")
    print(f"  Max: {price_max}")
    print(f"  Average: {price_avg:.2f}")
    print(f"  Range: {price_range} ticks")
    print(f"  Std Dev: {df['price'].std():.2f}")
    print(f"\nVolume Statistics:")
    print(f"  Total Volume: {df['quantity'].sum():,}")
    print(f"  Average Trade Size: {df['quantity'].mean():.2f}")
    print(f"  Max Trade Size: {df['quantity'].max()}")
    print(f"\nPrice Change Statistics:")
    print(f"  Average Change: {price_changes.mean():.2f} ticks")
    print(f"  Std Dev: {price_changes.std():.2f} ticks")
    print(f"  Max Up Move: {price_changes.max()} ticks")
    print(f"  Max Down Move: {price_changes.min()} ticks")
    print("="*70)


def main():
    """Main entry point."""
    # Determine CSV file to use
    if len(sys.argv) > 1:
        csv_file = sys.argv[1]
        if not os.path.exists(csv_file):
            print(f"Error: File not found: {csv_file}")
            sys.exit(1)
    else:
        csv_file = find_latest_csv()
        if not csv_file:
            print("Error: No price_data_seed_*.csv file found in data/ directory")
            print("Usage: python tools/visualize_price_data.py [csv_file]")
            sys.exit(1)
        print(f"Using latest CSV file: {csv_file}")
    
    # Load data
    print(f"Loading price data from: {csv_file}")
    try:
        df = load_price_data(csv_file)
        print(f"Loaded {len(df):,} trades")
    except Exception as e:
        print(f"Error loading CSV file: {e}")
        sys.exit(1)
    
    # Extract seed from filename if possible
    seed = extract_seed_from_filename(csv_file)
    if seed:
        print(f"Detected seed: {seed}")
    
    # Create visualizations
    output_dir = os.path.dirname(csv_file) or "data"
    create_visualizations(df, output_dir, seed)
    
    print("\nVisualization complete!")


if __name__ == "__main__":
    main()

